apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: gloo-rollout-demo
  namespace: gloo-rollout-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gloo-rollout-demo
  template:
    metadata:
      labels:
        app: gloo-rollout-demo
    spec:
      containers:
      - image:  kodacd/argo-rollouts-demo-api:v1
        imagePullPolicy: IfNotPresent
        name: gloo-rollout-demo
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
  strategy:
    canary:
      canaryService: canary
      stableService: stable
      trafficRouting:
        plugins:
          solo-io/glooplatformAPI:
            routeTableSelector:
              labels:
                app: demo
              # name: rt-name
              # namespace: rt-namespace
            routeSelector:
              labels:
                route: demo-preview
              # name: route-name

      steps:
      - setWeight: 10
      - pause: {}
      - setWeight: 50
      - pause: {}
      - setWeight: 100