---
apiVersion: v1
kind: Service
metadata:
  name: stable
  namespace: gloo-rollout-demo
  labels:
    app: gloo-rollout-demo
    service: gloo-rollout-demo
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 80
  selector:
    app: gloo-rollout-demo
