# .github/workflows/release.yaml

on: [push]
  # release:
  #   types: [created]

jobs:
  release-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Set short git commit SHA
      #   id: vars
      #   run: |
      #     calculatedSha=$(git rev-parse --short ${{ github.sha }})
      #     echo "::set-output name=short_sha::$calculatedSha"
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: go.sum
      - name: Build
        run: GOOS=linux GOARCH=amd64 go build -o rollouts-plugin-trafficrouter-glooplatform-linux-amd64 .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: rollouts-plugin-trafficrouter-glooplatform-linux-amd64